export const rockKickRoutes = [
  { checked: false,
    value: 'a',
    name: 'radio button a',
    number: 1
  },
  { checked: false,
    value: 'b',
    name: 'radio button b',
    number: 2
  },
  { checked: false,
    value: 'c',
    name: 'radio button ',
    number: 3
  },
  { checked: false,
    value: 'd',
    name: 'radio button a',
    number: 4,
  },
  { checked: false,
    value: 'e',
    name: 'radio button b',
    number: 5
  },
  { checked: false,
    value: 'f',
    name: 'radio button',
    number: 6
  },
  { checked: false,
    value: 'g',
    name: 'radio button a',
    number: 7,
  },
  { checked: false,
    value: 'h',
    name: 'radio button b',
    number: 8
  },
    { checked: false,
    value: 'i',
    name: 'radio button a',
    number: 9
  },
  { checked: false,
    value: 'j',
    name: 'radio button b',
    number: 10
  },
  { checked: false,
    value: 'k',
    name: 'radio button ',
    number: 11
  },
  { checked: false,
    value: 'l',
    name: 'radio button a',
    number: 12,
  },
  { checked: false,
    value: 'm',
    name: 'radio button b',
    number: 13
  },
  { checked: false,
    value: 'n',
    name: 'radio button',
    number: 14
  },
  { checked: false,
    value: 'o',
    name: 'radio button a',
    number: 15,
  },
  { checked: false,
    value: 'p',
    name: 'radio button b',
    number: 16
  },
  ]

//export const rockKickRoutes


export const rockSnareRoutes = [
  { checked: false,
    value: 'a',
    name: 'radio button a',
    number: 1
  },
  { checked: false,
    value: 'b',
    name: 'radio button b',
    number: 2
  },
  { checked: false,
    value: 'c',
    name: 'radio button ',
    number: 3
  },
  { checked: false,
    value: 'd',
    name: 'radio button a',
    number: 4,
  },
  { checked: false,
    value: 'e',
    name: 'radio button b',
    number: 5
  },
  { checked: false,
    value: 'f',
    name: 'radio button',
    number: 6
  },
  { checked: false,
    value: 'g',
    name: 'radio button a',
    number: 7,
  },
  { checked: false,
    value: 'h',
    name: 'radio button b',
    number: 8
  },
    { checked: false,
    value: 'i',
    name: 'radio button a',
    number: 9
  },
  { checked: false,
    value: 'j',
    name: 'radio button b',
    number: 10
  },
  { checked: false,
    value: 'k',
    name: 'radio button ',
    number: 11
  },
  { checked: false,
    value: 'l',
    name: 'radio button a',
    number: 12,
  },
  { checked: false,
    value: 'm',
    name: 'radio button b',
    number: 13
  },
  { checked: false,
    value: 'n',
    name: 'radio button',
    number: 14
  },
  { checked: false,
    value: 'o',
    name: 'radio button a',
    number: 15,
  },
  { checked: false,
    value: 'p',
    name: 'radio button b',
    number: 16
  },
  ]


export const rockOpenHatRoutes = [
  { checked: false,
    value: 'a',
    name: 'radio button a',
    number: 1
  },
  { checked: false,
    value: 'b',
    name: 'radio button b',
    number: 2
  },
  { checked: false,
    value: 'c',
    name: 'radio button ',
    number: 3
  },
  { checked: false,
    value: 'd',
    name: 'radio button a',
    number: 4,
  },
  { checked: false,
    value: 'e',
    name: 'radio button b',
    number: 5
  },
  { checked: false,
    value: 'f',
    name: 'radio button',
    number: 6
  },
  { checked: false,
    value: 'g',
    name: 'radio button a',
    number: 7,
  },
  { checked: false,
    value: 'h',
    name: 'radio button b',
    number: 8
  },
    { checked: false,
    value: 'i',
    name: 'radio button a',
    number: 9
  },
  { checked: false,
    value: 'j',
    name: 'radio button b',
    number: 10
  },
  { checked: false,
    value: 'k',
    name: 'radio button ',
    number: 11
  },
  { checked: false,
    value: 'l',
    name: 'radio button a',
    number: 12,
  },
  { checked: false,
    value: 'm',
    name: 'radio button b',
    number: 13
  },
  { checked: false,
    value: 'n',
    name: 'radio button',
    number: 14
  },
  { checked: false,
    value: 'o',
    name: 'radio button a',
    number: 15,
  },
  { checked: false,
    value: 'p',
    name: 'radio button b',
    number: 16
  },
  ]
  //export rockSnareRoutes
